- frameworks/react/package.json
This pr fixes an issue where installing the react npm package when using react 17 fails due to dependency conflict
> Update react version to be ^16.8.3 || ^17.0.0

- frameworks/svelte/__tests__/responsive.test.ts
- frameworks/svelte/__tests__/testUtils/ResponsiveHelperWrapper.svelte
- frameworks/svelte/__tests__/testUtils/testUtils.ts
This is the exact responsive tests we have for the react sdk, but for svelte.
> Add responsive unit tests for svelte sdk

- frameworks/angular/projects/cloudinary-library/src/lib/cloudinary.module.ts
ng-reflect-${name} attributes are added for debugging purposes and show the input bindings that a component/directive has declared in its class.
They exist only when debugging mode is used which is default mode for Angular. To disable them, we added  enableProdMode() which results in the following
> added enableProdMode()

- frameworks/vue/vue3/package.json
- Bumped version manually to beta.3 (to align with others)
- Add rollup Dev Dependency
> Add rollup devDependency to vue3 project

- frameworks/svelte/package.json
Remove the files property from svelte's package.json
We're currently publishing from ./dist, which means these files don't exist, and that causes an empty package to publish (since there are no matched files).
Publishing from `./dist` will probably change when we move to a MonoRepo, but for now this aligns svelte to the other frameworks.
> remove-files-property-from-svelte-package.json

- packages/angular/tsconfig.json
resolve broken ts imports
Since we're publishing dist we need to resolve the imports. 
right now we're getting an error with import {CloudinaryModule} from '@cloudinary/angular/';
meaning we need to include dist in our path  import {CloudinaryModule} from '@cloudinary/angular/';
to solve this we updated the tsconfig to the correct location
> resolve broken ts imports

- packages/html/src/layers/htmlImageLayer.ts
- packages/html/src/layers/htmlVideoLayer.ts
- packages/html/src/plugins/placeholder.ts
- packages/html/src/utils/serverSideSrc.ts
This pr fixes import of lodash.clonedeep.
The import was from lodash/clonedeep, even though lodash.clonedeep is a dependency (see package.json)
> Fix import of lodash.clonedeep

- packages/angular/projects/cloudinary-library/src/tests/accessibility.spec.ts
- packages/angular/projects/cloudinary-library/src/tests/placeholder.spec.ts
- packages/angular/projects/cloudinary-library/src/tests/responsive.spec.ts
- packages/html/src/plugins/accessibility.ts
- packages/html/src/plugins/lazyload.ts
- packages/html/src/plugins/placeholder.ts
- packages/html/src/plugins/responsive.ts
- packages/react/__tests__/accessibility.test.tsx
- packages/react/__tests__/lazyload.test.tsx
- packages/react/__tests__/placeholder.test.tsx
- packages/react/__tests__/responsive.test.tsx
We want to future-proof our plugins so that we can add a config option as input in the future. 
Our plugins now accept the input as an object rather than parameters
> add-plugin-input-as-object

- packages/html/src/plugins/responsive.ts
- packages/react/__tests__/responsive.test.tsx
---
React, Angular
This PR solves the default behavour of the responsive plugin.
- Before this PR, the first render of the responsive plugin would render an image with the width of the parent container.
- After this PR is merged, the responsive plugin will always respect the steps to define the width of the image on an initial render.
> Responsive Plugin will now respect steps to define max width

- packages/html/package.json
- packages/html/src/index.ts
- packages/html/src/layers/htmlImageLayer.ts
- packages/html/src/layers/htmlVideoLayer.ts
- packages/html/src/plugins/accessibility.ts
- packages/html/src/plugins/lazyload.ts
- packages/html/src/plugins/placeholder.ts
- packages/html/src/plugins/responsive.ts
- packages/html/src/utils/cancelCurrentlyRunningPlugins.ts
- packages/html/src/utils/internalConstants.ts
- packages/html/src/utils/render.ts
- packages/html/src/utils/serverSideSrc.ts
HTML
We're fixing svelte build requirements.
1. need to have .js extensions in order for svelte builds to find the path. 
2. according to svelte we need to have type="module" when exporting an esm otherwise the build fails. 
See #101 for more info
> fix svelte build requirements

- packages/angular/projects/cloudinary-library/src/lib/cloudinary.module.ts
cloudinary/ng
Removes production mode for Angular. 
Note that when using plugins we'll the plugins reflected in the dom. That being said users can easily remove if they use production mode-
> remove production mode

- packages/angular/projects/cloudinary-library/package.json
Angular
The pr should add `@angular/common` and `@angular/core` version 12 as valid peer dependencies.
According to https://angular.io/guide/releases#deprecation-practices all functionalities available in version 10, should also be available in version 12, unless you use some stuff which has been flagged as deprecated in version 8 and 9. Please feel free to decline the pr if this should be the case
> Add angular 12 as peer dependency

- packages/vue3/tests/unit/accessibility.spec.ts
- packages/vue3/tests/unit/utils.ts
> test: add vue3 accessibility tests

- packages/html/src/utils/serverSideSrc.ts
- packages/react/__tests__/analytics-ssr.test.tsx
- packages/react/src/AdvancedImage.tsx
HTML
React
In React SSR, the token changed to be the same as the token in CSR
> fix: use the same analytics token in react ssr and csr

- packages/html/src/layers/htmlImageLayer.ts
@cloudinary/html
Fixes html image layer errors when analytics is not provided. 
- [-] Tests - Add proper tests to the added code.
> fix: guard html image layer analytics options

- packages/react/src/AdvancedVideo.tsx
@cloudinary/react
change the type of `AdvancedVideo` props so they will include any valid `video` tag attributes
> fix: VideoProps to extend video tag attributes

- package.json
frontend-frameworks-monorepo 
Override the version of `sanitize-html`. Since `foodoc` isn't maintain anymore, we have to override it manually
> chore: override sanitize-html version

- e2e-tests/react-test-app/package.json
- package.json
All packages
- Moved all `devDependencies` incorrectly listed as `dependencies` which should fix all our security issues reported by Snyk
- No versions of packages were changed here
> chore: move docs packages to dev dependencies

- packages/html/__tests__/HtmlImageLayer.test.ts
- packages/html/src/layers/htmlImageLayer.ts
- packages/react/src/AdvancedImage.tsx
`@cloudinary/html`
`@cloudinary/react`
Add a fix to ensure the html layer is still in use when trying to update the `img` element.
In React 18 in `<StrictMode />`, the `lazyload` plugin does not work as expected. The issue is that since the plugin's promise is being resolved after a new instance of `HtmlImageLayer` is created, the previous `HtmlImageLayer` is updating the `img` element with the `src` which is not the expected behavior.
> fix: cleanup html layer on component unmount

- packages/html/__tests__/HtmlImageLayer.test.ts
- packages/html/src/plugins/placeholder.ts
@cloudinary/html
- Fix an issue where `placeholder` plugin causing extra request when used with analytics token
- Add a test to verify the token is the same in both phases of the rendering flow
> fix: fix placeholder plugin token

- packages/html/src/utils/render.ts
`@cloudinary/html`
Instead of returning the promise result inside the loop, returning the promise of the last plugin, which solve the issue when multiple plugins working together ends up in a wrong order of requests
> fix: return last plugin response

- packages/html/__tests__/HtmlImageLayer.test.ts
- packages/html/src/plugins/accessibility.ts
- packages/html/src/plugins/lazyload.ts
- packages/html/src/plugins/placeholder.ts
- packages/html/src/plugins/responsive.ts
- packages/html/src/types.ts
- packages/html/src/utils/render.ts
- playground/html/index.html
- playground/html/src/main.ts
@cloudinary/html
added functionality to avoid rendering responsive plugin when placeholder is added
> feat: added functionality to avoid rendering responsive plugin when placeholder is added

- packages/html/__tests__/HtmlImageLayer.test.ts
- packages/html/src/plugins/placeholder.ts
- packages/html/src/plugins/responsive.ts
- packages/html/src/utils/isPluginUsed.ts
- packages/html/src/utils/render.ts
- packages/vue/tests/unit/AdvancedImage.spec.ts
- playground/html/index.html
- playground/html/src/main.ts
* `@cloudinary/html`
* When responsive plugin is combined with placeholder it will fire additional request even before the placeholder image is fetched, see below before and after. 
* The first request is fired with different analytics than the second one and I'm not sure what is the expected one but we get rid of the first one so the second request (previously third) stays the same
> Make responsive plugin aware of placeholder to avoid duplicated requests

- packages/angular/package.json
- packages/angular/projects/cloudinary-library/package.json
- packages/angular/projects/cloudinary-library/src/tests/analytics.spec.ts
- packages/html/__tests__/HtmlImageLayer.test.ts
- packages/html/package.json
- packages/html/src/types.ts
- packages/react/__tests__/analytics-ssr.test.tsx
- packages/react/__tests__/analytics.test.tsx
- packages/react/package.json
- packages/vue/package.json
- packages/vue/tests/unit/analytics-ssr.spec.ts
- packages/vue/tests/unit/analytics.spec.ts
- @cloudinary/react
- @cloudinary/angular
- @cloudinary/vue
- @cloudinary/html
- Bumped version of `url-gen` package
- Updated tests for the new analytics algo
- Updated types definition for feature names
> fix: bump url-gen and update analytics related tests

- packages/html/src/plugins/lazyload.ts
html
fix an issue where `intersectionObserver` is not existed (for example in tests) the `unObserve` is not a function
> fix: ensure unobserve is a function

- packages/html/__tests__/HtmlVideoLayer.test.ts
- packages/html/src/layers/htmlVideoLayer.ts
- packages/html/src/types.ts
- packages/react/__tests__/AdvancedVideo.test.tsx
- packages/react/src/AdvancedVideo.tsx
- @cloudinary/html
- @cloudinary/react
- Adds a new prop and an option (in html package) to `useFetchFormat`
- When this option is enabled: 
- the extension is not added in the video sources
- the delivery format is set by `type`
> feat: add useFetchFormat prop in react sdk

- packages/vue/src/components/AdvancedVideo.vue
- packages/vue/tests/unit/AdvancedVideo.spec.ts
- @cloudinary/vue
- Adds a new property for video component: `useFetchFormat`
> feat: add useFetchFormat prop in vue sdk

- packages/angular/projects/cloudinary-library/src/lib/cloudinary-video.component.ts
- packages/angular/projects/cloudinary-library/src/tests/cloudinary-video.component.spec.ts
- @cloudinary/ng
- Adds a new property for video component: `useFetchFormat`
> feat: add useFetchFormat prop in angular sdk

- packages/angular/projects/cloudinary-library/src/lib/cloudinary-image.component.ts
- packages/angular/projects/cloudinary-library/src/tests/cloudinary-image.component.spec.ts
* @cloudinary/ng
* Follow up to https://github.com/cloudinary/frontend-frameworks/pull/235
* Synchronises empty image attributes including allowing to set empty string and remove attributes that have nullish values
* See this comment for more information: https://cloudinary.atlassian.net/browse/SNI-8216?focusedCommentId=355626
> fix: synchronize angular image empty attributes on updates

- packages/angular/projects/cloudinary-library/ng-package.json
- packages/angular/projects/cloudinary-library/ng-package.prod.json
- packages/angular/projects/cloudinary-library/package.json
- removed unused ng-package files
- changed dist -> . to have it resolved in the way before version 2.1.2
- added `files` property to package.json to filter out irrelevant files
> fix(angular): fixed publish configuration for angular workspace
