frameworks/svelte/__tests__/advancedImage.ssrtest.ts, frameworks/svelte/__tests__/testUtils/testUtils.ts, frameworks/svelte/jest-ssr.config.json, frameworks/svelte/package.json
Exact same tests from react sdk ssr tests were implemented
=> Add svelte ssr tests

frameworks/angular/projects/cloudinary-library/src/lib/cloudinary-video.component.ts, frameworks/angular/projects/cloudinary-library/src/tests/cloudinary-video.component.spec.ts, frameworks/html/src/types.ts, scripts/test.sh
1. Fixed broken types
2. fixed test script
3. updated angular tests
=> update broken build

frameworks/angular/projects/cloudinary-library/src/lib/cloudinary-video.component.ts
Aligned video attributes consumption in angular to react.
No functionality was changed but rather aligned the implementation so that when we look at both SDKs they have the same idea.
=> align video attributes

frameworks/angular/projects/cloudinary-library/src/lib/cloudinary-video.component.ts, frameworks/angular/projects/cloudinary-library/src/tests/cloudinary-video.component.spec.ts
Added onDestroy to Angular video component
Added test for update as well since it was missing
=> Added onDestroy to Angular video component

frameworks/angular/projects/cloudinary-library/package.json, frameworks/react/package.json, frameworks/svelte/package.json, frameworks/vue/vue3/package.json
updated to latest html version
=> updated to latest html version

packages/angular/package.json
=> remove private

.travis.yml, lerna.json, package.json, packages/angular/.gitignore, packages/angular/package.json, packages/angular/projects/cloudinary-library/ng-package.json, packages/react/playground/package.json
=> fix angular workspace

packages/angular/README.md, packages/html/README.md, packages/react/README.md
=> update readme for packages

package.json, packages/angular/package.json, packages/angular/projects/cloudinary-library/package.json, packages/html/package.json, packages/react/__tests__/AdvancedVideo.test.tsx, packages/react/package.json
=> Update url-gen version

packages/angular/projects/cloudinary-library/src/internal/SDKAnalyticsConstants.ts, packages/html/src/index.ts, packages/react/src/index.tsx
All
Add missing comments throughout the packages
=> Add comments in all packages

packages/angular/projects/cloudinary-library/src/lib/cloudinary-video.component.ts
Angular
Fix muted attribute on angular video
NOTE: This was tested manually as well to ensure expected behavior.
=> Fix muted attribute on angular video

packages/angular/projects/cloudinary-library/src/lib/cloudinary-video.component.ts, packages/angular/projects/cloudinary-library/src/tests/cloudinary-video.component.spec.ts
Angular 
Add video ref to Angular video
=> added video ref to Angular video  

packages/html/src/plugins/lazyload.ts, packages/html/src/plugins/placeholder.ts, packages/html/src/plugins/responsive.ts
HTML
Fixed wrong plugin jsdocs
=> Update plugin jsdocs

packages/html/src/plugins/placeholder.ts, packages/react/__tests__/ssr.test.tsx
HTML
Before this PR, The Placeholder plugin was ignored during SSR 
After this PR, SSR will correctly apply the placeholder transformations.
=> Placeholder plugin will now correctly run in SSR

package.json
For docs build 
fix jsdcos versions in package.json
=> fix jsdcos versions

package.json
docs build
fix better docs version in package.json
=> fix better docs version in package.json

packages/react/README.md, packages/react/package.json
React
Add Peer Dep of React 18 to React.
=> Add peer dep for react 18

packages/angular/README.md, packages/html/README.md, packages/react/README.md
=> Fix wrong README links

packages/angular/projects/cloudinary-library/package.json
=> fix version

packages/angular/package.json, packages/html/README.md, packages/react/package.json, packages/vue3/package.json
* Update description in package.json
* Update build script of vue3 sdk to copy package.json to /dist post build
* Update html layer README
=> chore: update package details

packages/react/README.md
React
Duplicate declaration of img
No new test required. Change only applies to readme.
=> Remove duplicate declaration of img

packages/react/README.md
Fixing documentation for example usage of AdvancedImage
... A few words
... A few words
=> docs: update readme

packages/angular/package.json, packages/angular/projects/cloudinary-library/package.json, packages/html/package.json, packages/react/package.json, packages/vue3/package.json
=> fix: update url-gen version

lerna.json, packages/angular/package.json
=> fix: fix the build

packages/vue3/README.md
=> fix: SNI-7113 formatting issue in Vue3 SDK Readme

packages/react/playground/.gitignore, packages/react/playground/README.md, packages/react/playground/index.html, packages/react/playground/package.json, packages/react/playground/src/App.css, packages/react/playground/src/App.tsx, packages/react/playground/src/index.css, packages/react/playground/src/index.tsx, packages/react/playground/src/main.tsx, packages/react/playground/src/react-app-env.d.ts, packages/react/playground/src/vite-env.d.ts, packages/react/playground/tsconfig.json, packages/react/playground/tsconfig.node.json, packages/react/playground/vite.config.ts
@cloudinary/react
Replace the broken React playground by using Vite template project
=> fix: fix react playground by using vite

packages/angular/README.md, packages/react/README.md, packages/vue3/README.md
All packages except the html package 
Fixed issues in readme (each commit for an issue)
=> Readme fixes

.travis.yml, packages/angular/package.json, packages/angular/projects/cloudinary-library/package.json, packages/html/package.json
`N/A`
Run CI against node 16 without allowing failures
=> Sni 6442 ci current node fixes

README.md
No specific package 
minor change in root  Readme formatting
=> fix: SNI-6918 minor code formatting issue

packages/vue/tests/unit/ssr.spec.ts
@cluodinary/vue
Adds SSR tests for Vue based on React's SSR test file.
=> test: add vue ssr spec

packages/vue/README.md
@cloudinary/vue
Added mentions about video component to the Vue README file (based on React package README)
=> Sni 6835 vue readme

packages/vue/tests/unit/analytics-ssr.spec.ts, packages/vue/tests/unit/analytics.spec.ts
- @cloudinary/vue
Skip vue dist tests. We don't need to test analytics here one more time in Vue.
=> test: skip vue dist tests

.github/workflows/pr-validate.yml
... A few words
... A few words
=> ci(config): Add whitespace
